#include "common/shaders_common.h"
#include "common/global_illumination/ddgi_common.h"

[[vk::binding(0, 3)]] ConstantBuffer<DDGIConstantBuffer>    ddgiCB;
[[vk::binding(1, 3)]] RWStructuredBuffer<DDGIProbeData>     ddgiProbesData;


[shader("compute")]
[numthreads(4, 4, 4)]
void main(uint3 DTid : SV_DispatchThreadID)
{
    float3 probesCoordinateStart = -((float3(ddgiCB.probesDimentions) * ddgiCB.probesWorldDistance) / 2);
    if (all(DTid < ddgiCB.probesDimentions))
    {
        uint sliceStart = ddgiCB.probesDimentions.x * ddgiCB.probesDimentions.y * DTid.z;
        uint columnStart = sliceStart + ddgiCB.probesDimentions.y * DTid.y;
        uint probeIndex = columnStart + DTid.x;

        DDGIProbeData probeData;
        probeData.position = float4(probesCoordinateStart + ddgiCB.probesWorldDistance * float3(DTid), 1.0);
        
        ddgiProbesData[probeIndex] = probeData;
    }
}