#include "common/shaders_common.h"
#include "common/screen_tracing.h"
#include "ambient_occlusion_type.h"

[[vk::binding(0, 3)]] RWTexture2D<float>    ao_output;
[[vk::binding(1, 3)]] Texture2D<float>      scene_depth;
[[vk::binding(2, 3)]] Texture2D<float4>     gBufferNormal_Metalness;

[[vk::binding(4, 3)]] RWTexture2D<float4>   DEBUG_TEXTURE;

struct PassUniform
{
    float4 aoStrength_KernelScale_MaxDistance;
    int4 aoVersion;
};
[[vk::binding(3, 3)]] ConstantBuffer<PassUniform> passUniform;

float GetAOStrength() { return passUniform.aoStrength_KernelScale_MaxDistance.x; }
float GetKernelScale() { return passUniform.aoStrength_KernelScale_MaxDistance.y; }
float GetMaxOcclusionDistance() { return passUniform.aoStrength_KernelScale_MaxDistance.z; }
AOVersion GetAOVersion() { return AOVersion(passUniform.aoVersion.x); }


[shader("compute")]
[numthreads(8, 8, 1)]
void main(uint3 DTid : SV_DispatchThreadID)
{
    int2 coords = int2(DTid.xy);
    float2 centerUV = ConvertScreenToUV(coords);
    float centerDeviceZSample = scene_depth.SampleLevel(GetSamplerNearestClamp(), centerUV, 0);
    float centerViewZ = ConvertDeviceZToViewZ(centerDeviceZSample);

    float3 centerWS = ConvertUVToWorld(centerUV, centerDeviceZSample);

    float3 normalWS = normalize((gBufferNormal_Metalness.SampleLevel(GetSamplerNearestClamp(), centerUV, 0).xyz - 0.5) * 2);

    static int SAMPLE_COUNT = 8;
    static float RADIAL_STEP = (2 * PI) / SAMPLE_COUNT;
    static float AO_DEPTH_THRESHOLD = 1;

    float2 uvRadius = GetKernelScale() / GetViewportSize();
    int marchStepCount = int(ceil(GetKernelScale()));
    float2 uvRayMarchStep = uvRadius / marchStepCount;

    AOVersion aoVersion = GetAOVersion();

    // my first attempt to do a horizon-based
    if (aoVersion == AOVersion::AO_DotBased)
    {

        float ambientOcclusionAccum = float(SAMPLE_COUNT);
        for(int i = 0; i < SAMPLE_COUNT; i++)
        {
            for (int step = 1; step < marchStepCount; step++)
            {
                float2 marchUV = RadialKernel(centerUV, i * RADIAL_STEP, uvRayMarchStep * step);
                float deviceZSample = scene_depth.SampleLevel(GetSamplerLinearClamp(), marchUV, 0);

                float zView = ConvertDeviceZToViewZ(deviceZSample);

                float3 marchWS = ConvertUVzViewToWorld(marchUV, zView);
                float3 marchedSampleDirection = normalize(marchWS - centerWS);

                float horizonAngle = dot(marchedSampleDirection, normalWS);
                if (horizonAngle >= 0.01)
                {
                    ambientOcclusionAccum -= horizonAngle * GetAOStrength();
                    break; // go to the next direction
                }
            }
        }

        ambientOcclusionAccum /= SAMPLE_COUNT;

        ao_output[coords] = ambientOcclusionAccum;
    }

    // second iteration of horizon-based
    else if (aoVersion == AOVersion::AO_HorizonBased)
    {
        float3 centerWorldPos = ConvertUVToWorld(centerUV, centerDeviceZSample);

        float ambientOcclusionAccum = float(SAMPLE_COUNT);
        for(int i = 0; i < SAMPLE_COUNT; i++)
        {
            for (int step = 1; step < marchStepCount; step++)
            {
                float2 marchUV = RadialKernel(centerUV, i * RADIAL_STEP, uvRayMarchStep * step);
                float deviceZSample = scene_depth.SampleLevel(GetSamplerNearestClamp(), marchUV, 0);

                float zView = ConvertDeviceZToViewZ(deviceZSample);

                float3 marchWorldPos = ConvertUVzViewToWorld(marchUV, zView);
                if (distance(marchWorldPos, centerWorldPos) > GetMaxOcclusionDistance())
                {
                    continue;
                }

                float3 marchedSampleDirection = normalize(marchWorldPos - centerWorldPos);

                float horizonAngle = dot(marchedSampleDirection, normalWS);
                if (horizonAngle >= 0.01)
                {
                    ambientOcclusionAccum -= horizonAngle * GetAOStrength();
                    break; // go to the next direction
                }
            }
        }

        ambientOcclusionAccum /= SAMPLE_COUNT;

        ao_output[coords] = ambientOcclusionAccum;
    }
    else if (aoVersion == AOVersion::AO_GTAO)
    {
        float3 centerVS = ConvertScreenToView(coords, centerDeviceZSample);
        float3 cameraDirVS = normalize(-centerVS);

        float3 normalVS = mul(GetCameraViewM(), float4(normalWS, 0)).xyz;

        const float C_SEGMENTS = 32;
        static float C_RADIAL_STEP = (PI * 2) / C_SEGMENTS;

        float visibility = 1;
        float occlusion = 0;
        for(int i = 0; i < C_SEGMENTS; i++)
        {
            float3 sampleDirVS = { 0, 0, 0 };
            sincos(i * C_RADIAL_STEP, sampleDirVS.x, sampleDirVS.y);
            float3 sampleDirOrhtoVS = sampleDirVS - cameraDirVS * dot(sampleDirVS, cameraDirVS);

            ScreenTracingParams traceParams;
            traceParams.surfacePosUV = centerUV;
            traceParams.traceDirUV = (sampleDirVS.xy / abs(centerViewZ)) * GetKernelScale();
            traceParams.surfacePosVS = centerVS;
            traceParams.surfaceNormalVS = normalVS;
            traceParams.traceDistanceVS = 1;
            traceParams.maxStepsCount = 6;

            float horizonAngle = saturate(TraceScreenDepthForHorizon(traceParams, scene_depth));
            //horizonAngle = 0.5;
            occlusion += cos(horizonAngle);
        }

        visibility -= (occlusion / C_SEGMENTS);

        // reintroduce lost luminance!

        ao_output[coords] = visibility;
        DEBUG_TEXTURE[coords] = float4(normalWS, 1);
        //ao_output[coords] = float(coords.x) / GetViewportSize().x;
    }
    else
    {
        ao_output[coords] = 1;
    }

    
    //ao_output[coords] = 1;
}