#include "common/shaders_common.h"

[[vk::binding(0, 3)]] RWTexture2D<float>   ao_output;
[[vk::binding(1, 3)]] Texture2D<float>     scene_depth;

struct PassUniform
{
    float4 ao_strength;
};
[[vk::binding(2, 3)]] ConstantBuffer<PassUniform> passUniform;

float GetAOStrength() { return passUniform.ao_strength.x; }

[shader("compute")]
[numthreads(8, 8, 1)]
void main(uint3 DTid : SV_DispatchThreadID)
{
    int2 coords = int2(DTid.xy);

    float currentDepth = scene_depth[coords];

    float aoTerm = currentDepth * GetAOStrength();
    ao_output[coords] = aoTerm;
}