#include "common/shaders_common.h"

[[vk::binding(0, 3)]] RWTexture2D<float4> outputTexture;

[[vk::binding(1, 3)]] Texture2D texture_h0;
[[vk::binding(2, 3)]] Texture2D texture_hkt;
[[vk::binding(3, 3)]] Texture2D texture_height;
[[vk::binding(4, 3)]] Texture2D texture_pingpong;

[numthreads(8, 8, 1)]
void main(uint3 DTid : SV_DispatchThreadID)
{
	int2 coords = int2(DTid.xy);
	float2 uv = float2(coords) / 256;

	float4 value = texture_pingpong.SampleLevel(GetSamplerLinear(), uv, 0);
	
	if(coords.x > 255 * 3)
	{
		value = texture_h0.SampleLevel(GetSamplerLinear(), uv, 0);
	}
	else if(coords.x > 255 * 2)
	{
		value = texture_hkt.SampleLevel(GetSamplerLinear(), uv, 0);
	}
	else if(coords.x > 255)
	{
		value = texture_pingpong.SampleLevel(GetSamplerLinear(), uv, 0);
	}
	else if(coords.x < 255)
	{
		value = texture_height.SampleLevel(GetSamplerLinear(), uv, 0);
	}
	
	outputTexture[coords] = value;
	
}