#include "common/shaders_common.h"
#include "debug_view.h"
#include "common/global_illumination/ddgi_common.h"

float4 RemapDisplayValue(float4 value, float lowBound, float highBound)
{
    float distance = highBound - lowBound;
    return (value - lowBound) / distance;
}

[numthreads(8, 8, 1)]
void main(uint3 DTid : SV_DispatchThreadID)
{
    //if (IsDDGIProbesDebugView(debugViewArgs))
    {
        uint probeIndex = DTid.x * 8 + DTid.y;

        if (probeIndex == 0)
        {
            indirectArgBuffer[0].vertexCount = 3; // WRITE SPHERES VERTEX COUNT HERE
            indirectArgBuffer[0].firstVertex = 0;
            indirectArgBuffer[0].firstInstance = 0;
        }

        if (probeIndex < debugViewArgs.probeCount)
        {
            atomicAdd(indirectArgBuffer[0].instanceCount, 1u);
        }
    }


}