#include "common/shaders_common.h"

[[vk::binding(0, 3)]] Texture2D<int4> butterflyTexture;
[[vk::binding(1, 3)]] Texture2D<float2> fftInput;
[[vk::binding(2, 3)]] RWTexture2D<float2> fftOutput;

struct Data
{
    float4 isVertical_stage;
};
[[vk::binding(3, 3)]] ConstantBuffer<Data> data;

struct complex
{
    float r;
    float i;
};

complex add(complex lhs, complex rhs)
{
    return complex(lhs.r + rhs.r, lhs.i + rhs.i);
}

complex multiply(complex lhs, complex rhs)
{
    return complex(lhs.r * rhs.r - lhs.i * rhs.i, lhs.r * rhs.i + lhs.i * rhs.r);
}

complex conjugate(complex x)
{
    return complex(x.r, -x.i);
}

[numthreads(8, 8, 1)]
void main(int2 DTid : SV_DispatchThreadID)
{
    int2 coords = DTid;

    bool isVertical = data.isVertical_stage.x > 0.5;
    int stage = int(data.isVertical_stage.y);

    if (isVertical)
    {
        int4 butterflyData = butterflyTexture[int2(stage, coords.y)];
        int2 paramsCoords = butterflyData.zw;
        complex w = complex(butterflyData.x, butterflyData.y);

        float2 inp0 = fftInput[int2(coords.x, paramsCoords.x)];
        float2 inp1 = fftInput[int2(coords.x, paramsCoords.y)];

        complex G = complex(inp0.x, inp0.y);
        complex H = complex(inp1.x, inp1.y);

        complex result = add(G, multiply(w, H));

        fftOutput[coords] = float2(result.r, result.i);
    }
    else 
    {
        int4 butterflyData = butterflyTexture[int2(stage, coords.x)];
        int2 paramsCoords = butterflyData.zw;
        complex w = complex(butterflyData.x, butterflyData.y);

        float2 inp0 = fftInput[int2(paramsCoords.x, coords.y)];
        float2 inp1 = fftInput[int2(paramsCoords.y, coords.y)];
    
        complex G = complex(inp0.x, inp0.y);
        complex H = complex(inp1.x, inp1.y);

        complex result = add(G, multiply(w, H));

        fftOutput[coords] = float2(result.r, result.i);
    }
}