set(GFX_HEADER_LIST
	"${DRE_SOURCE_DIR}/include/gfx/DeviceChild.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/FrameID.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/GraphicsManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/buffer/BufferBase.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/buffer/PersistentStorage.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/buffer/ReadbackProxy.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/buffer/StorageBuffer.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/buffer/TransientArena.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/buffer/UniformProxy.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/DDGI.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/BasePass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/AntiAliasingPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/AmbientOcclusionPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/CausticPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/ColorEncodingPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/DebugPassTextureView.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/DebugPassPrimitives.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/EditorPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/ForwardOpaquePass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/GBufferPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/ImGuiRenderPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/LightingPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/ShadowPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/WaterPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/FFTWaterPass.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pass/PassID.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pipeline/PipelineDB.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pipeline/PipelineEntry.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/pipeline/ResourceBinder.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/DrawBatcher.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/GPUInstanceAllocator.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/GlobalGeometryManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/GPULightsManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/RayTracingManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/RenderableObject.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/GPUMaterialsManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/Material.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/renderer/GPUInstanceManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/scheduling/DependencyManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/scheduling/GraphDescriptorManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/scheduling/GraphResource.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/scheduling/GraphResourcesManager.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/scheduling/RenderGraph.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/texture/TextureBank.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/texture/Texture.hpp"
	"${DRE_SOURCE_DIR}/include/gfx/view/RenderView.hpp")
	
set(GFX_SOURCE_LIST
	"${DRE_SOURCE_DIR}/src/gfx/DeviceChild.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/GraphicsManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/buffer/BufferBase.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/buffer/PersistentStorage.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/buffer/ReadbackProxy.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/buffer/StorageBuffer.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/buffer/UniformProxy.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/DDGI.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/BasePass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/AntiAliasingPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/AmbientOcclusionPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/CausticPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/ColorEncodingPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/DebugPassTextureView.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/DebugPassPrimitives.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/EditorPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/ForwardOpaquePass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/GBufferPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/ImGuiRenderPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/LightingPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/ShadowPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/WaterPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pass/FFTWaterPass.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pipeline/PipelineDB.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pipeline/PipelineEntry.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/pipeline/ResourceBinder.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/DrawBatcher.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/GlobalGeometryManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/GPULightsManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/RayTracingManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/RenderableObject.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/GPUMaterialsManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/Material.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/renderer/GPUInstanceManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/scheduling/DependencyManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/scheduling/GraphDescriptorManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/scheduling/GraphResourcesManager.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/scheduling/RenderGraph.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/texture/TextureBank.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/texture/Texture.cpp"
	"${DRE_SOURCE_DIR}/src/gfx/view/RenderView.cpp")

set(GFX_SHADER_LIST
	"${DRE_SOURCE_DIR}/shaders/common/global_illumination/ddgi_common.slang"
	"${DRE_SOURCE_DIR}/shaders/common/global_illumination/ddgi_probe_border_blend.slang"
	"${DRE_SOURCE_DIR}/shaders/common/global_illumination/ddgi_probe_lighting.slang"
	"${DRE_SOURCE_DIR}/shaders/common/global_illumination/ddgi_probe_scatter.slang"
	"${DRE_SOURCE_DIR}/shaders/common/global_illumination/ddgi_probe_trace.slang"
	"${DRE_SOURCE_DIR}/shaders/common/lighting/lighting_model.slang"
	"${DRE_SOURCE_DIR}/shaders/common/lighting/lighting.slang"
	"${DRE_SOURCE_DIR}/shaders/common/lighting/lights.slang"
	"${DRE_SOURCE_DIR}/shaders/common/shadows/shadows.slang"
	"${DRE_SOURCE_DIR}/shaders/common/utils/octahedron.slang"
	"${DRE_SOURCE_DIR}/shaders/common/utils/poisson.slang"
	"${DRE_SOURCE_DIR}/shaders/common/vertex/dre_vertex_layout.slang"
	"${DRE_SOURCE_DIR}/shaders/common/debug_draw.slang"
	"${DRE_SOURCE_DIR}/shaders/common/forward.slang"
	"${DRE_SOURCE_DIR}/shaders/common/global_uniform.slang"
	"${DRE_SOURCE_DIR}/shaders/common/instances.slang"
	"${DRE_SOURCE_DIR}/shaders/common/materials.slang"
	"${DRE_SOURCE_DIR}/shaders/common/screen_tracing.slang"
	"${DRE_SOURCE_DIR}/shaders/common/shaders_common.slang"
	"${DRE_SOURCE_DIR}/shaders/common/shaders_defines.slang"
	"${DRE_SOURCE_DIR}/shaders/ambient_occlusion_type.slang"
	"${DRE_SOURCE_DIR}/shaders/ambient_occlusion.slang"
	"${DRE_SOURCE_DIR}/shaders/color_encode.slang"
	"${DRE_SOURCE_DIR}/shaders/debug_primitives.slang"
	"${DRE_SOURCE_DIR}/shaders/debug_view_ddgi_probes.slang"
	"${DRE_SOURCE_DIR}/shaders/debug_view_texture.slang"
	"${DRE_SOURCE_DIR}/shaders/fft_inv_perm.slang"
	"${DRE_SOURCE_DIR}/shaders/fft_iter.slang"
	"${DRE_SOURCE_DIR}/shaders/fft_water_uniform.slang"
	"${DRE_SOURCE_DIR}/shaders/forward_pbr.slang"
	"${DRE_SOURCE_DIR}/shaders/forward_shadow.slang"
	"${DRE_SOURCE_DIR}/shaders/gbuffer_pbr.slang"
	"${DRE_SOURCE_DIR}/shaders/gen_butterfly.slang"
	"${DRE_SOURCE_DIR}/shaders/gen_h0.slang"
	"${DRE_SOURCE_DIR}/shaders/gen_hxt.slang"
	"${DRE_SOURCE_DIR}/shaders/gizmo_3D.slang"
	"${DRE_SOURCE_DIR}/shaders/gizmo_3D_shared.slang"
	"${DRE_SOURCE_DIR}/shaders/imgui_old.slang"
	"${DRE_SOURCE_DIR}/shaders/lighting_deferred.slang"
	"${DRE_SOURCE_DIR}/shaders/temporal_AA.slang"
	"${DRE_SOURCE_DIR}/shaders/water_caustics.slang"
	"${DRE_SOURCE_DIR}/shaders/water_shadow.slang"
	"${DRE_SOURCE_DIR}/shaders/water.slang")

add_library(gfx STATIC ${GFX_HEADER_LIST} ${GFX_SOURCE_LIST})

target_include_directories(gfx PUBLIC "${DRE_SOURCE_DIR}/include" "${DRE_SOURCE_DIR}/shaders")

target_sources(gfx PRIVATE ${GFX_SHADER_LIST})
set_source_files_properties(${GFX_SHADER_LIST} PROPERTIES
	VS_TOOL_OVERRIDE "FXCompile"
	VS_SETTINGS "ExcludedFromBuild=true") #doesn't work, I'll have to rename all files to proper extensions for smth like this to work. Most likely I won't even need these lines afterwards

source_group(
	TREE "${DRE_SOURCE_DIR}/shaders"
	PREFIX "Shader Files"
	FILES ${GFX_SHADER_LIST})


target_compile_features(gfx PUBLIC cxx_std_20)
target_compile_definitions(gfx PUBLIC WIN32_LEAN_AND_MEAN NOMINMAX)
#TODO: disable exceptions

target_link_libraries(gfx PUBLIC foundation engine vk_wrapper glm_static imgui)

source_group(
	TREE "${DRE_SOURCE_DIR}/include/gfx"
	PREFIX "Header Files"
	FILES ${GFX_HEADER_LIST})